global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: /metrics

  - job_name: 'pedidos'
    static_configs:
      - targets: ['pedidos:8080']
    metrics_path: /metrics

  - job_name: 'pagamentos'
    static_configs:
      - targets: ['pagamentos:8080']
    metrics_path: /metrics

  - job_name: 'estoque'
    static_configs:
      - targets: ['estoque:8080']
    metrics_path: /metrics
